services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - /var/lib/redis/:/data

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"
