services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - backend/.env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - ./redis/data/:/data
